# Generated by Django 3.0 on 2019-12-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Input File')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('dete_uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Date Uploaded')),
            ],
        ),
    ]
