# Generated by Django 3.0 on 2019-12-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputfile',
            name='status',
            field=models.CharField(choices=[('queued', 'queued'), ('processing', 'processing'), ('done', 'done'), ('error', 'error')], default='queued', max_length=50, verbose_name='Staus'),
        ),
    ]
