# Generated by Django 3.0 on 2019-12-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotapp', '0003_inputfile_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputfile',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='', verbose_name='PDF File'),
        ),
    ]
